/***************************************************************************//**
* File Name: cycfg_gap.c
*
* Description:
* BLE device's GAP configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.60.0.1460
*
********************************************************************************
* Copyright 2023 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gap.h"
#include "cycfg_gatt_db.h"
#include "cycfg_bt_settings.h"
#include "wiced_bt_sdp_defs.h"

wiced_bt_ble_advert_type_t app_adv_flag = BTM_BLE_LIMITED_DISCOVERABLE_FLAG | BTM_BLE_BREDR_NOT_SUPPORTED;
uint16_t app_adv_service     = UUID_SERVCLASS_LE_HID;

wiced_bt_ble_advert_elem_t cy_bt_adv_packet_data[] =
{
    // flag
    [0].advert_type  = BTM_BLE_ADVERT_TYPE_FLAG,
    [0].len          = sizeof(uint8_t),
    [0].p_data       = &app_adv_flag,

    // Appearance
    [1].advert_type  = BTM_BLE_ADVERT_TYPE_APPEARANCE,
    [1].len          = sizeof(uint16_t),
    [1].p_data       = (uint8_t *)&wiced_bt_cfg_settings.gatt_cfg.appearance,

    //16 bits Service: UUID_SERVCLASS_LE_HID
    [2].advert_type  = BTM_BLE_ADVERT_TYPE_16SRV_COMPLETE,
    [2].len          = sizeof(uint16_t),
    [2].p_data       = (uint8_t *)&app_adv_service,

    //dev name
    [3].advert_type  = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE,
    [3].len          = 11,
    [3].p_data       = app_gap_device_name,
};
